export const items = [
    {
      id: 1,
      title: 'Miniatur Handmade',
      priceRange: 'Rp50k-200k',
      location: 'Jakarta Utara',
      rating: 5,
      sold: 1000,
      image: '/jual1.png',
      sponsor: true,
      description: "Saya udah cape 24 jam ngoding T___T"
    },
    {
      id: 2,
      title: 'Comission Lukisan Realistis',
      priceRange: 'Rp150k-500k',
      location: 'Jakarta Pusat',
      rating: 5,
      sold: 200,
      image: '/jual2.png',
      sponsor: true,
      description: "lorem ipsum dolor sit amet. capek banget T___T wah udah capek banget",
    },
    {
      id: 3,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual3.png',
      sponsor: true,
      description: "lorem ipsum dolor sit amet. hai aku capek banget T___T",
    },
    {
      id: 4,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual4.png',
      sponsor: true,
      description: "lorem ipsum dolor sit amet. halo aku capek banget T___T",
    },
    {
      id: 5,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual5.png',
      sponsor: false,
      description: "lorem ipsum dolor sit amet. test capek banget T___T",
    },
    {
      id: 6,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual1.png',
      sponsor: false,
      description: "lorem ipsum dolor sit amet. test capek banget T___T",
    },
    {
      id: 7,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual2.png',
      sponsor: false,
      description: "lorem ipsum dolor sit amet. gimana capek banget T___T",
    },
    {
      id: 8,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual3.png',
      sponsor: false,
      description: "lorem ipsum dolor sit amet, capek banget T___T",
    },
    {
      id: 9,
      title: 'Kerajinan Tangan',
      priceRange: 'Rp20k-100k',
      location: 'Jakarta Barat',
      rating: 4,
      sold: 500,
      image: '/jual4.png',
      sponsor: false,
      description: "lorem ipsum dolor sit amet, wdqw capek banget T___T",
    },
  ];
  